POST http://localhost:8080/events
content-type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAcS5jb20iLCJleHAiOjE3NDAzMjQ3MTUsInVzZXJJZCI6Mn0._QWIwRq8jegTCkQS_FZn4JhJ-Po0p55xeHL7CJQRN84


{
  "name": "BBQ event!",
  "description": "A BBQ event",
  "location": "A test location",
  "dateTime": "2025-01-01T15:30:00.000Z"
}