DELETE http://localhost:8080/events/2
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAcS5jb20iLCJleHAiOjE3NDAzMjY1MjcsInVzZXJJZCI6Mn0.W4mURMMMFZP2QCeHA-Ca0_FlQhlzoLE614lOALKZYmM
